version: '3.8'

services:
  discord-datamining:
    build: .
    container_name: discord_datamining_bot
    restart: unless-stopped
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh:ro
    environment:
      - TZ=Asia/Seoul
